import * as THREE from 'three';
/* Level generated by ChatGPT for testing purposes */
class Test {
    constructor() {
        this.scene = new THREE.Scene();
        this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
        this.camera.position.set(0, 10, 30);

        this.clock = new THREE.Clock();

        this.cube = null; // Initialize cube as null
    }

    init() {
        // Scene setup
        var ambientLight = new THREE.AmbientLight(0xffffff, 1);
        this.scene.add(ambientLight);

        var directionalLight = new THREE.DirectionalLight(0xffffff, 1);
        directionalLight.position.set(10, 30, 10);
        this.scene.add(directionalLight);

        // Add a rotating cube for visual confirmation
        var cubeGeometry = new THREE.BoxGeometry(5, 5, 5);
        var cubeMaterial = new THREE.MeshStandardMaterial({ color: 0xff0000 });
        this.cube = new THREE.Mesh(cubeGeometry, cubeMaterial);
        this.cube.position.set(0, 5, 0);
        this.scene.add(this.cube);
    }

    update(deltaTime) {
        if (this.cube) { // Check if cube exists
            // Rotate the cube for visual feedback
            this.cube.rotation.x += deltaTime;
            this.cube.rotation.y += deltaTime;
        }
    }

    clear() {
        // Remove and dispose the cube if it exists
        if (this.cube) {
            this.scene.remove(this.cube);
            this.cube.geometry.dispose();
            this.cube.material.dispose();
            this.cube = null; // Nullify the reference
        }

        // Clean up other objects in the scene
        this.scene.traverse((object) => {
            if (object.geometry) object.geometry.dispose();
            if (object.material) object.material.dispose();
        });
    }
}

export default Test;
